[build]
  publish = "static"
  command = "yarn build"

[build.environment]
NODE_VERSION = "14"

[functions]
  directory = "functions"

[functions."ssr"]
  included_files = [
    ".nuxt/**",
    "node_modules/@storefront-ui/**",
    "serverMiddleware/**"
    ]

[[redirects]]
  from = "spryker/*"
  to = "/.netlify/functions/middleware"
  status = 200

[[redirects]]
  from = "/*"
  query = {ebPreview = ":ebPreview"}
  to = "/__query_ebPreview"
  force = true
  status = 301

[[redirects]]
  from = "/*"
  to = "/.netlify/builders/ssr"
  status = 200
